### ISSUE TITLE
Strange error while running the script

### ISSUE THREAD

**Issue by Gyslainh** [vMarkusK/Advanced-PRTG-Sensors#60] opened 2020-07-13 14:23 UTC
C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : 
Cannot convert the "System.Object[]" value of type "System.Object[]" to type 
"System.Guid".
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom 
sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Veeam.ps1
 
C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : 
at <ScriptBlock>, C:\Program Files (x86)\PRTG Network Monitor\custom 
sensors\EXEXML\Veeam.ps1: line 532
at <ScriptBlock>, <No file>: line 1
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom 
sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Veeam.ps1
 

That happens in PRTG and if i run the script manually

**Comment by vMarkusK** [comment] 2020-07-13 17:29
Hi @Gyslainh ,

I have a few questions:
- do you use the latest version from the GitHub Repo?
- Which Veeam Version do you use?
- Hase the script ever worked fine in your environment?
-- Is so. What has changed recently?

**Comment by Gyslainh** [comment] 2020-07-14 09:52
Hi yes I used the latest version I’ll check again to be sure

As for now it’s veeam 9.5u4B
We have multiple clients on PRTG this is the only one that doesn’t seem to work

Ps does your script works with veeam 10?


________________________________
De : Markus Kraus <notifications@github.com>
Envoyé : mardi, juillet 14, 2020 5:07 a.m.
À : vMarkusK/Advanced-PRTG-Sensors
Cc : Gyslainh; Mention
Objet : Re: [vMarkusK/Advanced-PRTG-Sensors] Strange error while running the script (#60)


Hi @Gyslainh<https://github.com/Gyslainh> ,

I have a few questions:

  *   do you use the latest version from the GitHub Repo?
  *   Which Veeam Version do you use?
  *   Hase the script ever worked fine in your environment?
-- Is so. What has changed recently?

**Comment by Gyslainh** [comment] 2020-07-14 11:02
Getting this with the new script

At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:329 char:21
+         <svg class="octicon octicon-sign-out v-align-middle" viewBox="0 0 16
16" ...
+                     ~~~~~~~
Unexpected token 'octicon' in expression or statement.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:404 char:62
+   src="https://avatars2.githubusercontent.com/u/67691026?s=60&amp;v=4"
+                                                              ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:408 char:18
+     <span class="dropdown-caret"></span>
+                  ~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'dropdown-caret"></span>
  </summary>
  <details-menu class="dropdown-menu' in expression or statement.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:414 char:124
+ ... tatus?compact=1&amp;link_mentions=0&amp;truncate=1">
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:414 char:144
+ ... link_mentions=0&amp;truncate=1">
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:420 char:58
+       role="menuitem"
data-hydro-click="{&quot;event_type&quot;:&quot;user_profi ...
+                                                          ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:420 char:65
+       role="menuitem"
data-hydro-click="{&quot;event_type&quot;:&quot;user_profi ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:420 char:89
+ ... r_profile.click&quot;,&quot;payload&quot;:{&quot;profile_user_id&quot;:16
706362, ...
+                    ~
The ampersand (&) character is not allowed. The & operator is reserved for
future use; wrap an ampersand in double quotation marks ("&") to pass it as
part of a string.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:420 char:96
+ ... le.click&quot;,&quot;payload&quot;:{&quot;profile_user_id&quot;:16706362,
&quot;t ...
+                    ~
Missing expression after unary operator ','.
At C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1:420 char:96
+ ... le.click&quot;,&quot;payload&quot;:{&quot;profile_user_id&quot;:16706362,
&quot;t ...
+                    ~
Unexpected token '&' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken





Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by vMarkusK** [comment] 2020-07-14 17:44
> Ps does your script works with veeam 10?
Yes, it does work with v10.

Are you sure that there is no Copy & Paste issue with the content of the PS1?
Just to make true, please use this view and copy & past it again:
https://raw.githubusercontent.com/vMarkusK/Advanced-PRTG-Sensors/master/Veeam/PRTG-VeeamBRStats.ps1

Is there an obvious difference between the environments?
- Special Characters in Jobs ar Repos
- Job Types
- Inventory Onjects
- etc.

**Comment by Gyslainh** [comment] 2020-07-14 17:51
Nope getting this error now

C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : Failed to connect to Veeam BR Host
'172.21.1.183' with user 'computername$'
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Veeam.ps1
C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : at <ScriptBlock>, C:\Program Files
(x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1: line 203
at <ScriptBlock>, <No file>: line 1
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Veeam.ps1
<prtg>
<error>1</error>
<text>Failed to connect to Veeam BR Host '172.21.1.183' with user 'CNMDC1$'</text>
</prtg>


Environnement is about the same for everyone either windows 2012R2 or 2016

This Probe doesn’t have the veeam server on it it,s on another server



Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by Gyslainh** [comment] 2020-07-14 19:12
I’m also getting this error at other places

C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 :
Method invocation failed because [Veeam.Backup.Core.CBackupRepository] does
not contain a method named 'GetRepositoryBackupsSize'.
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1' ' ...

none are Veeam 10 all are 9.5U4B




Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by vMarkusK** [comment] 2020-07-14 19:48
Now the script works as intended. A copy & paste error must have crept in.

> C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : Failed to connect to Veeam BR Host
'172.21.1.183' with user 'computername$'

This a connection error to the Veeam Server. Please verify the Connection from this Host to the VBR Server via the VBR Console with the same Credentials.

> C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 :
Method invocation failed because [Veeam.Backup.Core.CBackupRepository] does
not contain a method named 'GetRepositoryBackupsSize'.

This error occurs, when you run this script against a Veeam Backup & Replication Server prior Version 10 with connected Cloud Connect Repositories.

**Comment by Gyslainh** [comment] 2020-07-14 19:54
Now the script works as intended. A copy & paste error must have crept in.

C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : Failed to connect to Veeam BR Host
'172.21.1.183' with user 'computername$'

If I run the script directly from the probe with the same username I have 0 problems its PRTG that give me that error




C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 :
Method invocation failed because [Veeam.Backup.Core.CBackupRepository] does
not contain a method named 'GetRepositoryBackupsSize'.

This error occurs, when you run this script against a Veeam Backup & Replication Server prior Version 10 with connected Cloud Connect Repositories.
But I have a lot of other users with Cloud connect Repositories and they work fine, why would this one give me that error and how to fix it?

Thanks a lot for your script and your time its’ appreciated




Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by vMarkusK** [comment] 2020-07-14 20:17
Other users fixed the connection issue by changing the probe service from local system to a named account that has access to veeam. Otherwise you can als configure the credentials for the device in PRTG.

Latest version of the script only works with cloud connect repos and version 10 and older versions only supported up to 9.5 U4 with cloud connect repos.

**Comment by Gyslainh** [comment] 2020-07-15 11:13
Ok so I’ll have to use a earlier version to work with 9.5U4B Cloud repo ok thanks




Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by vMarkusK** [comment] 2020-07-15 16:51
Are you fine with that solution?

If so, I will close this issue.

**Comment by Gyslainh** [comment] 2020-07-15 16:54
No as the error stands

C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : Cannot convert the "System.Object[]"
value of type "System.Object[]" to type "System.Guid".
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Veeam.ps1
C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 : at <ScriptBlock>, C:\Program Files
(x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1: line 532
at <ScriptBlock>, <No file>: line 1
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Veeam.ps1


This one happens on a client hwere the probe is the same server as the Veeam 9.5U4B

I tried changing the login for the probe service and made sure the windows credentials are good (used a domain admin account) and still doesn’t work

This is a 2012R2 server




Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by vMarkusK** [comment] 2020-07-15 18:30
Might you please verify this enhanced version on your v10 and v9.5 VBR Server?
https://raw.githubusercontent.com/vMarkusK/Advanced-PRTG-Sensors/MultVeeamVersion/Veeam/PRTG-VeeamBRStats.ps1

`./PRTG-VeeamBRStats.ps1 -Debug`

There was a Bug in the older version of the script if multiple cloud repos are connected. Does this apply to your environment?

**Comment by Gyslainh** [comment] 2020-07-15 18:43
Hi, it indeed fixed the one that had multiple cloud repo but the one that has a single cloud repo still fails

C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 :
Cannot convert the "System.Object[]" value of type "System.Object[]" to type
"System.Guid".
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Veeam.ps1
C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\Veeam.ps1 :
at <ScriptBlock>, C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1: line 550
at <ScriptBlock>, <No file>: line 1
At line:1 char:1
+ &'C:\Program Files (x86)\PRTG Network Monitor\custom
sensors\EXEXML\Veeam.ps1' ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Veeam.ps1

This is the last one left to fix




Gyslain Hamel
Administrateur de Système/System Administrator

[cid:image001.png@01D2BDDA.DCDB3780]

[cid:image003.png@01D5AE7A.E31E6200]<https://www.canadianbusiness.com/lists-and-rankings/growth-500/2019-information-technology-fastest-growing-companies/>

www.equipemicrofix.com<http://www.equipemicrofix.com/>
Bureau/Office: 514-394-0780
Sans-Frais/Toll-Free: 1-855-305-9939
Fax: 450-933-6229



[mcsa-windows-server-2016-certified-2020]<https://www.youracclaim.com/badges/ac59d77b-9209-48da-bf7a-dfadeaa187c3/public_url>

**Comment by vMarkusK** [comment] 2020-07-15 18:57
To fix the issue I need a bit more detailed feedback.

- v10 [Failed|Okay]
-- Single Cloud Repo [Failed|Okay]
-- Multiple Cloud Vepo [Failed|Okay]
- v 9.5 [Failed|Okay]
-- Single Cloud Repo [Failed|Okay]
-- Multiple Cloud Repo [Failed|Okay]

Might you please also share the Error and Debug output if possible?
Do you use the new version (https://raw.githubusercontent.com/vMarkusK/Advanced-PRTG-Sensors/MultVeeamVersion/Veeam/PRTG-VeeamBRStats.ps1)  of the script on all VBR Servers within this test?

**Closed** 2022-03-02 21:07 UTC
Labels: question
